export const [
    SET_PROPERTIES,
    CREATE_PROPERTY,
    UPDATE_PROPERTY,
    DELETE_PROPERTY,
    SET_PROPERTIES_COUNT_BY_CITY,
    SET_PROPERTIES_COUNT_BY_CATEGORY
] = [
    'SET_PROPERTIES',
    'CREATE_PROPERTY',
    'UPDATE_PROPERTY',
    'DELETE_PROPERTY',
    'SET_PROPERTIES_COUNT_BY_CITY',
    'SET_PROPERTIES_COUNT_BY_CATEGORY'
]
